sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
      - maven_central
linkReplacements:
  - LICENSE-exasol-jdbc.txt|https://www.exasol.com/support/secure/attachment/155343/EXASOL_SDK-7.0.11.tar.gz
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"