sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
      - maven_central
build:
  runnerOs: ubuntu-20.04
  exasolDbVersions:
    - "7.1.25"
